name: week-4-project

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        working-directory: week-4-project/exercises
      - name: Build app
        run: npm run build --if-present
        working-directory: week-4-project/exercises
      - name: Run Tests
        run: npm test
        working-directory: week-4-project/exercises
        env:
          CI: true
